#!/bin/bash

# {{@@ header() @@}}

# Load configuration files
[ -f ~/.config/bash/bashrc ] && source ~/.config/bash/bashrc
[ -f ~/.config/bash/ls_colors ] && source ~/.config/bash/ls_colors
[ -f ~/.config/bash/monitors.env ] && source ~/.config/bash/monitors.env

# Load other programs' configurations
[ -f ~/.cargo/env ] && source ~/.cargo/env
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -f /usr/share/fzf/key-bindings.bash ] && source /usr/share/fzf/key-bindings.bash
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

# Load completions
[ -f /usr/share/bash-completion/completions/git ] && source /usr/share/bash-completion/completions/git
[ -f /usr/share/bash-completion/completions/diesel ] && source /usr/share/bash-completion/completions/diesel
if command -v pandoc 2>&1 > /dev/null ; then eval "$(pandoc --bash-completion)"; fi
[ -f /usr/share/fzf/completion.bash ] && source /usr/share/fzf/completion.bash
if command -v just 2>&1 > /dev/null ; then eval "$(just --completions bash)"; fi
