#!/bin/bash

# {{@@ header() @@}}

# Load configuration files
[ -f ~/.config/bash/bashrc ] && source ~/.config/bash/bashrc
[ -f ~/.config/bash/ls_colors ] &&  source ~/.config/bash/ls_colors

# Load fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Load other programs' configurations
[ -f "~/.cargo/env" ] && source "~/.cargo/env"

# Load completions
[ -f /usr/share/bash-completion/completions/git ] && source /usr/share/bash-completion/completions/git
if command -v pandoc 2>&1 > /dev/null ; then eval "$(pandoc --bash-completion)"; fi
