#!/usr/bin/env sh
# {{@@ header() @@}}

xset -b
xset r rate 150 50

~/.config/i3/scripts/monitor/export_monitor_names_to_file.sh

$HOME/.fehbg &
ffplay $HOME/startup.mp3 -nodisp -autoexit > /dev/null 2>&1 < /dev/null &
