config:
  backup: false
  banner: true
  create: true
  dotpath: ../dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  import_configs:
    - dotfiles.yaml
    - profiles.yaml
  diff_command: "delta --color-only --paging never {0} {1}"
dotfiles:
profiles:
