config:
  backup: false
  banner: true
  create: true
  dotpath: ../dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
dotfiles:
profiles:
  tty-only:
    dotfiles:
      - f_config_ranger_scope.sh
      - f_config_ranger_rc.conf
      - f_config_ranger_commands_full.py
      - f_config_ranger_commands.py
      - f_config_ranger_rifle.conf
      - f_config_nvim_coc-settings.json
      - f_config_nvim_init.vim
      - f_config_nvim_settings.vim
      - f_config_nvim_lua_config.lua
      - f_config_nvim_lua_ethi_luatelescope_extensions_ethi.lua
      - f_config_nvim_lua_mappings.lua
      - f_config_nvim_lua_plugins.lua
      - f_config_nvim_lua_utils.lua
      - f_config_nvim_lua_lsp_init.lua
      - f_config_nvim_lua_lsp_rust-analyzer.lua
      - f_config_nvim_lua_lsp_sumneko_lua.lua
      - f_config_nvim_lua_plugin_cfg_compe.lua
      - f_config_nvim_lua_plugin_cfg_fzf.lua
      - f_config_nvim_lua_plugin_cfg_lsp-trouble.lua
      - f_config_nvim_lua_plugin_cfg_nvim-colorizer.lua
      - f_config_nvim_lua_plugin_cfg_startify.lua
      - f_config_nvim_lua_plugin_cfg_telescope.lua
      - f_config_nvim_lua_plugin_cfg_tokyonight.lua
      - f_config_nvim_lua_plugin_cfg_treesitter.lua
      - f_config_nvim_lua_plugin_cfg_ts-rainbow.lua
      - f_config_nvim_lua_plugin_cfg_ultisnips.lua
      - f_config_nvim_lua_plugin_cfg_vim-airline.lua
      - f_config_nvim_lua_plugin_cfg_vim-stay.lua
      - f_config_nvim_UltiSnips_c.snippets
      - f_config_nvim_UltiSnips_make.snippets
      - f_config_nvim_UltiSnips_text.snippets
      - f_config_nvim_UltiSnips_tex.snippets
      - f_config_nvim_UltiSnips_plaintex.snippets
      - f_config_nvim_UltiSnips_cmake.snippets
      - f_config_nvim_UltiSnips_java.snippets
      - f_config_nvim_UltiSnips_cpp.snippets
      - f_local_bin_sleepuntil
      - f_bashrc
      - f_config_bash_bashrc
      - f_config_bash_ls_colors
  gui:
    variables:
      is_gui: true
    include:
      - tty-only
    dotfiles:
      - f_Xresources
      - f_config_i3_config
      - f_Xdefaults
      - f_local_bin_i3lock-select
      - f_local_bin_play
      - f_local_bin_scrot_region
      - f_local_bin_i3lock-rand
      - f_local_bin_srofi_run
      - f_xinitrc
  Tswarra:
    variables:
      is_homestation: true
      is_i3_gaps: true
      has_colout: true
    include:
      - gui
  Kanto:
    variables:
      is_homestation: true
      has_colout: true
    include:
      - tty-only
  hawkeye:
    variables:
      is_i3_gaps: false
      has_colout: true
      is_homestation: false
      is_workstation: true
    include:
      - gui
