config:
  backup: false
  banner: true
  create: true
  dotpath: ../dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
dotfiles:
profiles:
  tty-only:
    dotfiles:
      - f_bashrc
      - f_config_bash_bashrc
      - f_config_bash_ls_colors
      - f_config_gitui_key_bindings.ron
      - f_config_gitui_theme.ron
      - f_config_nvim_init.vim
      - f_config_nvim_lua_config.lua
      - f_config_nvim_lua_ethi_lua_telescope__extensions_ethi.lua
      - f_config_nvim_lua_lsp_init.lua
      - f_config_nvim_lua_lsp_rust-analyzer.lua
      - f_config_nvim_lua_lsp_sumneko_lua.lua
      - f_config_nvim_lua_lsp_texlab.lua
      - f_config_nvim_lua_mappings.lua
      - f_config_nvim_lua_plugin-cfg_fzf.lua
      - f_config_nvim_lua_plugin-cfg_git-messenger.lua
      - f_config_nvim_lua_plugin-cfg_lualine.lua
      - f_config_nvim_lua_plugin-cfg_nvim-cmp.lua
      - f_config_nvim_lua_plugin-cfg_nvim-colorizer.lua
      - f_config_nvim_lua_plugin-cfg_startify.lua
      - f_config_nvim_lua_plugin-cfg_telescope.lua
      - f_config_nvim_lua_plugin-cfg_todo-comments.lua
      - f_config_nvim_lua_plugin-cfg_treesitter.lua
      - f_config_nvim_lua_plugin-cfg_trouble.lua
      - f_config_nvim_lua_plugin-cfg_ts-rainbow.lua
      - f_config_nvim_lua_plugin-cfg_vim-better-whitespace.lua
      - f_config_nvim_lua_plugin-cfg_vim-rooter.lua
      - f_config_nvim_lua_plugin-cfg_vim-stay.lua
      - f_config_nvim_lua_plugin-cfg_vsnip.lua
      - f_config_nvim_lua_plugins.lua
      - f_config_nvim_lua_utils.lua
      - f_config_nvim_settings.vim
      - f_config_nvim_snippets_c.json
      - f_config_nvim_snippets_cpp.json
      - f_config_nvim_snippets_html.json
      - f_config_nvim_snippets_latex.json
      - f_config_nvim_snippets_lua.json
      - f_config_nvim_snippets_python_base.json
      - f_config_nvim_snippets_python_comprehension.json
      - f_config_nvim_snippets_python_debug.json
      - f_config_nvim_snippets_python_python.json
      - f_config_nvim_snippets_python_unittest.json
      - f_config_nvim_snippets_rust.json
      - f_config_ranger_commands_full.py
      - f_config_ranger_commands.py
      - f_config_ranger_rc.conf
      - f_config_ranger_rifle.conf
      - f_config_ranger_scope.sh
      - f_config_yt-dlp_config
      - f_gitconfig
      - f_local_bin_sleepuntil
  gui:
    variables:
      is_gui: true
    include:
      - tty-only
    dotfiles:
      - f_config_alacritty_alacritty.yml
      - f_config_dunst_dunstrc
      - f_config_gammastep_config.ini
      - f_config_i3_config
      - f_config_i3_scripts_export_monitor_names_to_file.sh
      - f_config_polybar_bars.ini
      - f_config_polybar_colors.ini
      - f_config_polybar_config.ini
      - f_config_polybar_launch.sh
      - f_config_polybar_modules_battery.ini
      - f_config_polybar_modules_cpu.ini
      - f_config_polybar_modules_custom_pipewire-control.ini
      - f_config_polybar_modules_date.ini
      - f_config_polybar_modules_filesystem.ini
      - f_config_polybar_modules_i3.ini
      - f_config_polybar_modules_memory.ini
      - f_config_polybar_modules_network.ini
      - f_config_polybar_modules_temperature.ini
      - f_config_polybar_modules_xkeyboard.ini
      - f_config_polybar_modules_xwindow.ini
      - f_config_polybar_scripts_pipewire-control.bash
      - f_config_polybar_scripts_pipewire-control.bash
      - f_local_bin_dothelock
      - f_local_bin_i3lock-rand
      - f_local_bin_i3lock-select
      - f_local_bin_play
      - f_local_bin_scrot_region
      - f_local_bin_srofi_run
      - f_local_bin_suspend
      - f_Xdefaults
      - f_xinitrc
      - f_xprofile
      - f_Xresources
  Tswarra:
    variables:
      # Whether the machine is mine at home.
      # For the things that are best not found on a workstation.
      is_homestation: true
      # Whether the machine is at work.
      # Kinda exclusive with is_homestation.
      is_workstation: false
      # Whether the machine has a battery
      has_battery: true
      # Whether the machine has i3-gaps (does not apply to tty-only
      # configurations).
      has_i3_gaps: true
      # Whether the machine has taskwarrior.
      # Adds a summary of tasks on bash login.
      has_taskwarrior: true
      # Whether the machine has pip's colout package.
      # Controls compilation outputs.
      has_colout: true
      # Name of the wired network interface to display the status of in polybar
      polybar_wired_network_interface: enp0s31f6
      # Name of the wireless network interface to display the status of in polybar
      polybar_wireless_network_interface: wlp4s0
      # The git user name (user.name).
      git_config_user: Ethiraric
      # The git email (user.email).
      git_config_email: ethiraric@gmail.com
      # The monitor dunst is to use
      dunst_monitor: 0
      # Geometry of the notification box
      dunst_geometry: "300x10-20+40"
    include:
      - gui
  kanto:
    variables:
      is_homestation: true
      has_colout: true
      git_config_user: Ethiraric
      git_config_email: ethiraric@gmail.com
    include:
      - tty-only
  Jotho:
    dotfiles:
      - f_screenlayout_default.sh
    variables:
      is_homestation: true
      has_colout: true
      has_i3_gaps: true
      has_taskwarrior: true
      polybar_wired_network_interface: enp4s0
      git_config_user: Ethiraric
      git_config_email: ethiraric@gmail.com
      dunst_monitor: 1
      dunst_geometry: "300x10-20+40"
    include:
      - gui
  hawkeye:
    variables:
      is_workstation: true
      has_colout: true
      has_i3_gaps: true
      has_taskwarrior: true
      polybar_wired_network_interface: enp5s0
      git_config_user: Florian Sabourin
      git_config_email: f.sabourin@alcom-tech.com
      dunst_monitor: 1
      dunst_geometry: "300x10-20+40"
    include:
      - gui
  vision:
    variables:
      is_workstation: true
      has_colout: true
      git_config_user: Florian Sabourin
      git_config_email: f.sabourin@alcom-tech.com
    include:
      - gui
